const NATIONALITY_ISO: Record<string, string> = {
  England: 'GB-ENG',
  Scotland: 'GB-SCT',
  Wales: 'GB-WLS',
  'Northern Ireland': 'GB-NIR',
  Brazil: 'BR',
  Argentina: 'AR',
  France: 'FR',
  Germany: 'DE',
  'West Germany': 'DE',
  'East Germany': 'DE',
  Italy: 'IT',
  Spain: 'ES',
  Portugal: 'PT',
  Netherlands: 'NL',
  Belgium: 'BE',
  Croatia: 'HR',
  Uruguay: 'UY',
  Colombia: 'CO',
  Chile: 'CL',
  Mexico: 'MX',
  'United States': 'US',
  Canada: 'CA',
  Morocco: 'MA',
  Algeria: 'DZ',
  Nigeria: 'NG',
  Senegal: 'SN',
  Ghana: 'GH',
  'Ivory Coast': 'CI',
  Cameroon: 'CM',
  Mali: 'ML',
  Egypt: 'EG',
  'South Africa': 'ZA',
  'Réunion': 'RE',
  Liberia: 'LR',
  Australia: 'AU',
  'New Zealand': 'NZ',
  Japan: 'JP',
  'South Korea': 'KR',
  'Saudi Arabia': 'SA',
  Turkey: 'TR',
  Russia: 'RU',
  Ukraine: 'UA',
  Poland: 'PL',
  'Czech Republic': 'CZ',
  Austria: 'AT',
  Switzerland: 'CH',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Finland: 'FI',
  Iceland: 'IS',
  Serbia: 'RS',
  'Serbia and Montenegro': 'RS',
  Greece: 'GR',
  Romania: 'RO',
  Hungary: 'HU',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Ireland: 'IE',
  'Republic of Ireland': 'IE',
  Ecuador: 'EC',
  Paraguay: 'PY',
  Bolivia: 'BO',
  Venezuela: 'VE',
  Peru: 'PE',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Honduras: 'HN',
  Jamaica: 'JM',
  'Trinidad and Tobago': 'TT',
  Albania: 'AL',
  'North Macedonia': 'MK',
  Yugoslavia: 'RS',
  'Bosnia and Herzegovina': 'BA',
  Montenegro: 'ME',
  Bulgaria: 'BG',
  Georgia: 'GE',
  Armenia: 'AM',
  Belarus: 'BY',
  Azerbaijan: 'AZ',
  Israel: 'IL',
  Iran: 'IR',
  Iraq: 'IQ',
  Zimbabwe: 'ZW',
  Togo: 'TG',
  'Burkina Faso': 'BF',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  'Equatorial Guinea': 'GQ',
  'DR Congo': 'CD',
  Congo: 'CG',
  'Republic of the Congo': 'CG',
  Zambia: 'ZM',
  Tanzania: 'TZ',
  Kenya: 'KE',
  Uganda: 'UG',
  Ethiopia: 'ET',
  Tunisia: 'TN',
  Libya: 'LY',
  Sudan: 'SD',
  Angola: 'AO',
  Mozambique: 'MZ',
  Madagascar: 'MG',
  Gabon: 'GA',
  Rwanda: 'RW',
  Benin: 'BJ',
  Niger: 'NE',
  Chad: 'TD',
  Somalia: 'SO',
  Eritrea: 'ER',
  Malawi: 'MW',
  Namibia: 'NA',
  Botswana: 'BW',
  Lesotho: 'LS',
  Eswatini: 'SZ',
  Mauritius: 'MU',
  'Cape Verde': 'CV',
  'Sierra Leone': 'SL',
  'Burkina': 'BF',
  China: 'CN',
  India: 'IN',
  Pakistan: 'PK',
  Indonesia: 'ID',
  Thailand: 'TH',
  Vietnam: 'VN',
  Malaysia: 'MY',
  Philippines: 'PH',
  Singapore: 'SG',
  'North Korea': 'KP',
  Kazakhstan: 'KZ',
  Uzbekistan: 'UZ',
  Qatar: 'QA',
  'United Arab Emirates': 'AE',
  Kuwait: 'KW',
  Jordan: 'JO',
  Lebanon: 'LB',
  Syria: 'SY',
  Cyprus: 'CY',
  Latvia: 'LV',
  Lithuania: 'LT',
  Estonia: 'EE',
  Luxembourg: 'LU',
  Moldova: 'MD',
  Kosovo: 'XK',
  Malta: 'MT',
  Liechtenstein: 'LI',
  Andorra: 'AD',
  'San Marino': 'SM',
  Cuba: 'CU',
  'Dominican Republic': 'DO',
  Haiti: 'HT',
  Guatemala: 'GT',
  'El Salvador': 'SV',
  Nicaragua: 'NI',
  Guyana: 'GY',
  Suriname: 'SR',
  Curaçao: 'CW',
}

export function nationalityToFlagUrl(nationality: string | null | undefined): string | null {
  if (!nationality) return null
  const iso = NATIONALITY_ISO[nationality]
  if (!iso) return null
  return `https://flagcdn.com/${iso.toLowerCase()}.svg`
}
