const NATIONALITY_ISO: Record<string, string> = {
  England: 'GB-ENG',
  Scotland: 'GB-SCT',
  Wales: 'GB-WLS',
  'Northern Ireland': 'GB-NIR',
  Brazil: 'BR',
  Argentina: 'AR',
  France: 'FR',
  Germany: 'DE',
  'West Germany': 'DE',
  'East Germany': 'DE',
  Italy: 'IT',
  Spain: 'ES',
  Portugal: 'PT',
  Netherlands: 'NL',
  Belgium: 'BE',
  Croatia: 'HR',
  Uruguay: 'UY',
  Colombia: 'CO',
  Chile: 'CL',
  Mexico: 'MX',
  'United States': 'US',
  Canada: 'CA',
  Morocco: 'MA',
  Algeria: 'DZ',
  Nigeria: 'NG',
  Senegal: 'SN',
  Ghana: 'GH',
  'Ivory Coast': 'CI',
  Cameroon: 'CM',
  'South Africa': 'ZA',
  Liberia: 'LR',
  Australia: 'AU',
  Japan: 'JP',
  'South Korea': 'KR',
  'Saudi Arabia': 'SA',
  Turkey: 'TR',
  Russia: 'RU',
  Ukraine: 'UA',
  Poland: 'PL',
  'Czech Republic': 'CZ',
  Austria: 'AT',
  Switzerland: 'CH',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Finland: 'FI',
  Iceland: 'IS',
  Serbia: 'RS',
  Greece: 'GR',
  Romania: 'RO',
  Hungary: 'HU',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Ireland: 'IE',
  'Republic of Ireland': 'IE',
  Ecuador: 'EC',
  Paraguay: 'PY',
  Bolivia: 'BO',
  Venezuela: 'VE',
  Peru: 'PE',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Honduras: 'HN',
  Jamaica: 'JM',
  Albania: 'AL',
  'North Macedonia': 'MK',
  Yugoslavia: 'YU',
  'Bosnia and Herzegovina': 'BA',
  Montenegro: 'ME',
  Bulgaria: 'BG',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Israel: 'IL',
  Iran: 'IR',
  Iraq: 'IQ',
}

export function nationalityToFlagUrl(nationality: string | null | undefined): string | null {
  if (!nationality) return null
  const iso = NATIONALITY_ISO[nationality]
  if (!iso) return null
  return `https://flagcdn.com/${iso.toLowerCase()}.svg`
}
