const NATIONALITY_ISO: Record<string, string> = {
  England: "GB-ENG",
  Scotland: "GB-SCT",
  Wales: "GB-WLS",
  "Northern Ireland": "GB-NIR",
  Brazil: "BR",
  Argentina: "AR",
  France: "FR",
  Germany: "DE",
  "West Germany": "DE",
  "East Germany": "DE",
  Italy: "IT",
  Spain: "ES",
  Portugal: "PT",
  Netherlands: "NL",
  Belgium: "BE",
  Croatia: "HR",
  Uruguay: "UY",
  Colombia: "CO",
  Chile: "CL",
  Mexico: "MX",
  "United States": "US",
  Canada: "CA",
  Morocco: "MA",
  Algeria: "DZ",
  Nigeria: "NG",
  Senegal: "SN",
  Ghana: "GH",
  "Ivory Coast": "CI",
  Cameroon: "CM",
  Mali: "ML",
  Egypt: "EG",
  "South Africa": "ZA",
  Réunion: "RE",
  Liberia: "LR",
  Australia: "AU",
  "New Zealand": "NZ",
  Japan: "JP",
  "South Korea": "KR",
  "Saudi Arabia": "SA",
  Turkey: "TR",
  Russia: "RU",
  Ukraine: "UA",
  Poland: "PL",
  "Czech Republic": "CZ",
  Austria: "AT",
  Switzerland: "CH",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Finland: "FI",
  Iceland: "IS",
  Serbia: "RS",
  "Serbia and Montenegro": "RS",
  Greece: "GR",
  Romania: "RO",
  Hungary: "HU",
  Slovakia: "SK",
  Slovenia: "SI",
  Ireland: "IE",
  "Republic of Ireland": "IE",
  Ecuador: "EC",
  Paraguay: "PY",
  Bolivia: "BO",
  Venezuela: "VE",
  Peru: "PE",
  "Costa Rica": "CR",
  Panama: "PA",
  Honduras: "HN",
  Jamaica: "JM",
  "Trinidad and Tobago": "TT",
  Albania: "AL",
  "North Macedonia": "MK",
  Yugoslavia: "__yugoslavia__",
  "FR Yugoslavia": "__yugoslavia__",
  "SFR Yugoslavia": "__yugoslavia__",
  "Bosnia and Herzegovina": "BA",
  Montenegro: "ME",
  Bulgaria: "BG",
  Georgia: "GE",
  Armenia: "AM",
  Belarus: "BY",
  Azerbaijan: "AZ",
  Israel: "IL",
  Iran: "IR",
  Iraq: "IQ",
  Zimbabwe: "ZW",
  Togo: "TG",
  "Burkina Faso": "BF",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  "Equatorial Guinea": "GQ",
  "DR Congo": "CD",
  Zaire: "CD",
  Congo: "CG",
  "Republic of the Congo": "CG",
  Zambia: "ZM",
  Tanzania: "TZ",
  Kenya: "KE",
  Uganda: "UG",
  Ethiopia: "ET",
  Tunisia: "TN",
  Libya: "LY",
  Sudan: "SD",
  Angola: "AO",
  Mozambique: "MZ",
  Madagascar: "MG",
  Gabon: "GA",
  Rwanda: "RW",
  Benin: "BJ",
  Niger: "NE",
  Chad: "TD",
  Somalia: "SO",
  Eritrea: "ER",
  Malawi: "MW",
  Namibia: "NA",
  Botswana: "BW",
  Lesotho: "LS",
  Eswatini: "SZ",
  Mauritius: "MU",
  "Cape Verde": "CV",
  "Sierra Leone": "SL",
  Burkina: "BF",
  China: "CN",
  India: "IN",
  Pakistan: "PK",
  Indonesia: "ID",
  Thailand: "TH",
  Vietnam: "VN",
  Malaysia: "MY",
  Philippines: "PH",
  Singapore: "SG",
  "North Korea": "KP",
  Kazakhstan: "KZ",
  Uzbekistan: "UZ",
  Qatar: "QA",
  "United Arab Emirates": "AE",
  Kuwait: "KW",
  Jordan: "JO",
  Lebanon: "LB",
  Syria: "SY",
  Cyprus: "CY",
  Latvia: "LV",
  Lithuania: "LT",
  Estonia: "EE",
  Luxembourg: "LU",
  Moldova: "MD",
  Kosovo: "XK",
  Malta: "MT",
  Liechtenstein: "LI",
  Andorra: "AD",
  "San Marino": "SM",
  Cuba: "CU",
  "Dominican Republic": "DO",
  Haiti: "HT",
  Guatemala: "GT",
  "El Salvador": "SV",
  Nicaragua: "NI",
  Guyana: "GY",
  Suriname: "SR",
  Curaçao: "CW",
  // Smaller FIFA nations (match the international-team names the scraper stores)
  "Faroe Islands": "FO",
  Gibraltar: "GI",
  "Antigua and Barbuda": "AG",
  Barbados: "BB",
  Bermuda: "BM",
  Grenada: "GD",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Cayman Islands": "KY",
  Montserrat: "MS",
  Dominica: "DM",
  Aruba: "AW",
  Belize: "BZ",
  Bahamas: "BS",
  "Turks and Caicos Islands": "TC",
  "British Virgin Islands": "VG",
  "U.S. Virgin Islands": "VI",
  Anguilla: "AI",
  "Puerto Rico": "PR",
  Gambia: "GM",
  "Central African Republic": "CF",
  Mauritania: "MR",
  "South Sudan": "SS",
  Burundi: "BI",
  Comoros: "KM",
  Seychelles: "SC",
  "São Tomé and Príncipe": "ST",
  Djibouti: "DJ",
  "Hong Kong": "HK",
  Myanmar: "MM",
  Cambodia: "KH",
  Laos: "LA",
  Brunei: "BN",
  Bangladesh: "BD",
  "Sri Lanka": "LK",
  Nepal: "NP",
  Maldives: "MV",
  Bhutan: "BT",
  Mongolia: "MN",
  "Chinese Taipei": "TW",
  Macau: "MO",
  Guam: "GU",
  Bahrain: "BH",
  Oman: "OM",
  Yemen: "YE",
  Palestine: "PS",
  Tajikistan: "TJ",
  Kyrgyzstan: "KG",
  Turkmenistan: "TM",
  Afghanistan: "AF",
  Fiji: "FJ",
  "Papua New Guinea": "PG",
  "New Caledonia": "NC",
  Tahiti: "PF",
  "Solomon Islands": "SB",
  Vanuatu: "VU",
  Samoa: "WS",
  "American Samoa": "AS",
  Tonga: "TO",
  "Cook Islands": "CK",
  // Adjective/demonym forms stored in the DB
  English: "GB-ENG",
  Scottish: "GB-SCT",
  Welsh: "GB-WLS",
  "Northern Irish": "GB-NIR",
  French: "FR",
  German: "DE",
  Spanish: "ES",
  Italian: "IT",
  Portuguese: "PT",
  Dutch: "NL",
  Belgian: "BE",
  Brazilian: "BR",
  Argentine: "AR",
  Argentinian: "AR",
  Colombian: "CO",
  Chilean: "CL",
  Uruguayan: "UY",
  Mexican: "MX",
  American: "US",
  Australian: "AU",
  "New Zealander": "NZ",
  Japanese: "JP",
  "South Korean": "KR",
  "Saudi Arabian": "SA",
  Turkish: "TR",
  Russian: "RU",
  Ukrainian: "UA",
  Polish: "PL",
  Czech: "CZ",
  Austrian: "AT",
  Swiss: "CH",
  Swedish: "SE",
  Norwegian: "NO",
  Danish: "DK",
  Finnish: "FI",
  Icelandic: "IS",
  Serbian: "RS",
  Greek: "GR",
  Romanian: "RO",
  Hungarian: "HU",
  Slovak: "SK",
  Slovenian: "SI",
  Irish: "IE",
  Ecuadorian: "EC",
  Paraguayan: "PY",
  Bolivian: "BO",
  Venezuelan: "VE",
  Peruvian: "PE",
  "Costa Rican": "CR",
  Panamanian: "PA",
  Honduran: "HN",
  Jamaican: "JM",
  Trinidadian: "TT",
  Albanian: "AL",
  Macedonian: "MK",
  Bosnian: "BA",
  Montenegrin: "ME",
  Bulgarian: "BG",
  Georgian: "GE",
  Armenian: "AM",
  Belarusian: "BY",
  Azerbaijani: "AZ",
  Israeli: "IL",
  Iranian: "IR",
  Iraqi: "IQ",
  Zimbabwean: "ZW",
  Togolese: "TG",
  Burkinabé: "BF",
  Guinean: "GN",
  Equatoguinean: "GQ",
  Congolese: "CD",
  Zambian: "ZM",
  Tanzanian: "TZ",
  Kenyan: "KE",
  Ugandan: "UG",
  Ethiopian: "ET",
  Tunisian: "TN",
  Libyan: "LY",
  Sudanese: "SD",
  Angolan: "AO",
  Mozambican: "MZ",
  Gabonese: "GA",
  Rwandan: "RW",
  Beninese: "BJ",
  Chadian: "TD",
  Somali: "SO",
  Eritrean: "ER",
  Malawian: "MW",
  Namibian: "NA",
  Motswana: "BW",
  Basotho: "LS",
  Mauritian: "MU",
  "Cape Verdean": "CV",
  "Sierra Leonean": "SL",
  Chinese: "CN",
  Indian: "IN",
  Pakistani: "PK",
  Indonesian: "ID",
  Thai: "TH",
  Vietnamese: "VN",
  Malaysian: "MY",
  Filipino: "PH",
  Singaporean: "SG",
  Kazakhstani: "KZ",
  Uzbekistani: "UZ",
  Qatari: "QA",
  Emirati: "AE",
  Kuwaiti: "KW",
  Jordanian: "JO",
  Lebanese: "LB",
  Syrian: "SY",
  Cypriot: "CY",
  Latvian: "LV",
  Lithuanian: "LT",
  Estonian: "EE",
  Luxembourgish: "LU",
  Moldovan: "MD",
  Kosovan: "XK",
  Maltese: "MT",
  Cuban: "CU",
  Dominican: "DO",
  Haitian: "HT",
  Guatemalan: "GT",
  Salvadoran: "SV",
  Nicaraguan: "NI",
  Guyanese: "GY",
  Surinamese: "SR",
  Ivorian: "CI",
  Cameroonian: "CM",
  Ghanaian: "GH",
  Nigerian: "NG",
  Senegalese: "SN",
  Malian: "ML",
  Moroccan: "MA",
  Algerian: "DZ",
  Egyptian: "EG",
  Liberian: "LR",
  Croatian: "HR",
};

const LOCAL_FLAGS: Record<string, string> = {
  __yugoslavia__: "/flags/yugoslavia.svg",
};

function isoToUrl(iso: string): string {
  // Self-hosted from /public/flags (downloaded from flagcdn) so flags don't
  // depend on the external CDN, which intermittently throttled in production.
  return LOCAL_FLAGS[iso] ?? `/flags/${iso.toLowerCase()}.svg`;
}

export function nationalityToFlagUrl(
  nationality: string | null | undefined,
): string | null {
  if (!nationality) return null;

  // Try exact match first
  const iso = NATIONALITY_ISO[nationality];
  if (iso) return isoToUrl(iso);
  // Handle multi-value strings like "Italy Australia" — return first recognised
  for (const part of nationality.split(/\s+/)) {
    const partIso = NATIONALITY_ISO[part];
    if (partIso) return isoToUrl(partIso);
  }

  return null;
}
